version: '3.8'

services:

  oss-frontend-service:
    image: ossfarm/oss-frontend-service:1.0-SNAPSHOT
    build: .
    container_name: oss-front-end
    restart: always
    ports:
      - 4200:80
    networks:
      - oss-network

networks:
  oss-network:
    driver: bridge
